FYProject1/Controllers/CartController.cs
using FYProject1Classes;
using FYProject1Classes.CartManagment;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Mail;
using System.Web.Mvc;
using FYProject1Classes.FinalOrderMgmt;
using FYProject1Classes.UserMgmt;

namespace FYProject1.Controllers
{
    public class CartController : Controller
    {
        // GET: Cart
        [HttpGet]
        public ActionResult ViewCart()
        {
            int total = 0;
            ShoppingCart cart = (ShoppingCart)Session[WebUtil.CART];

            if (cart != null && cart.NumberOfItems > 0)
            {
                var cartList = new List<ShoppingCartItem>();

                foreach (var c in cart.Items)
                {
                    ShoppingCartItem cartItem = new ShoppingCartItem
                    {
                        Id = c.Id,
                        Name = c.Name,
                        Price = c.Price,
                        Quantity = c.Quantity,
                        ImageURL = c.ImageURL,
                        Sale = c.Sale
                    };
                    cartList.Add(cartItem);
                    cartList.TrimExcess();
                    total += c.Amount;
                }
                ViewBag.total = total;
                return View(cartList);
            }

            return View();
        }

        [HttpGet]
        public int AddToCart(ShoppingCartItem item)
        {
            ShoppingCart cart = (ShoppingCart)Session[WebUtil.CART] ?? new ShoppingCart();

            cart.Add(item);
            Session.Add(WebUtil.CART, cart);

            return cart.NumberOfItems;
        }

        [HttpGet]
        public ActionResult RemoveFromCart(int id)
        {
            ShoppingCart cart = (ShoppingCart)Session[WebUtil.CART];
            if (cart != null)
            {
                cart.Remove(id);
                Session.Add(WebUtil.CART, cart);
            }
            return RedirectToAction("ViewCart");
        }

        public int UpdateToCart()
        {
            ShoppingCart cart = (ShoppingCart)Session[WebUtil.CART];
            if (cart != null)
            {
                cart.Update(Convert.ToInt32(Request.QueryString["id"]),
                            Convert.ToInt32(Request.QueryString["qty"]));
            }
            return cart.NumberOfItems;
        }

        public int ItemsCount()
        {
            ShoppingCart cart = (ShoppingCart)Session[WebUtil.CART];
            if (cart != null)
            {
                return cart.NumberOfItems;
            }
            return 0;
        }

        public ActionResult Checkout()
        {
            User currentUser = (User)Session[WebUtil.CURRENT_USER];

            //User currentUser = new UserHandler().GetUser(user.Id);

            FinalOrder fo = new FinalOrder();

            if (currentUser != null)
            {
                fo.Email = currentUser.Email;
                fo.FullAddress = currentUser.FullAddress;
                fo.Name = currentUser.FullName;
                fo.Phone = currentUser.Phone;

                return RedirectToAction("ConfirmOrder", fo);
            }
            return View();
        }

        [HttpPost]
        public ActionResult Checkout(FinalOrder order)
        {
            if (ModelState.IsValid)
            {
                return RedirectToAction("ConfirmOrder", order);
            }

            return View();
        }

        public ActionResult ConfirmOrder(FinalOrder order)
        {
            int total = 0;
            ShoppingCart cart = (ShoppingCart)Session[WebUtil.CART];

            if (cart != null && cart.NumberOfItems > 0)
            {

                foreach (var c in cart.Items)
                {
                    ShoppingCartItem cartItem = new ShoppingCartItem
                    {
                        Id = c.Id,
                        Name = c.Name,
                        Price = c.Price,
                        Quantity = c.Quantity,
                        ImageURL = c.ImageURL,
                        Sale = c.Sale
                    };
                    order.ShoppingCartItem.Add(cartItem);
                    total += c.Amount;
                }
                ViewBag.total = total;

            }
            return View(order);
        }

        public ActionResult PlaceOrder(FinalOrder order)
        {
            ShoppingCart cart = (ShoppingCart)Session[WebUtil.CART];

            if (cart != null && cart.NumberOfItems > 0)
            {

                foreach (var c in cart.Items)
                {
                    ShoppingCartItem cartItem = new ShoppingCartItem
                    {
                        Id = c.Id,
                        Name = c.Name,
                        Price = c.Price,
                        Quantity = c.Quantity,
                        ImageURL = c.ImageURL,
                        Sale = c.Sale
                    };
                    order.ShoppingCartItem.Add(cartItem);
                }

                order.OrderStatus = "Pending";
                dynamic randomNumber = Path.GetRandomFileName().Replace(".", "");
                order.OrderNumber = randomNumber;
            }
            new OrderHandler().AddOrder(order);
            Session.Clear();

            // Sending Product Email

            try
            {
                var message = new MailMessage();
                message.To.Add(new MailAddress(order.Email));
                message.Subject = "-No-Reply- Shopping Details";

                // BODY Making Here to Send HTML page in email.

                message.IsBodyHtml = true;

                string body = string.Empty;
                StreamReader reader = new StreamReader(Server.MapPath("~/Views/Cart/orderemail.html"));
                using (reader)
                {
                    body = reader.ReadToEnd();
                }

                body = body.Replace("{track}", order.OrderNumber);
                body = body.Replace("{username}", order.Name);
                
                message.Body = body;

                using (var smtp = new SmtpClient())
                {
                    smtp.Send(message);
                    ViewBag.success = "Email Has been sent to  " + order.Email;
                }
                return View(order);

            }
            catch (Exception)
            {
                ViewBag.error = "Error Sending Mail. Please Try Again Later!";
            }
            return View(order);
        }

        public int OrderCount()
        {
            DBContextClass db = new DBContextClass();
            using (db)
            {
                return (from c in db.FinalOrders select c).Count();
            }
        }
    }
}

FYProject1/Views/Cart/Checkout.cshtml
@model FYProject1Classes.FinalOrderMgmt.FinalOrder

@{
    ViewBag.Title = "Checkout";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}
@section myStyles{
    <style type="text/css">
        @@media screen and (min-width:992px) {
            .form-control {
                width: 40%;
            }
        }
    </style>
}

<h2 class="list-group-item-heading text-center notextselect">Checkout</h2>

<div class="col-lg-9">

    @using (Html.BeginForm("Checkout", "Cart", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Enter Your Details so we can proceed further to Checkout!</h4>
            <hr />
            <div>
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.FullAddress, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.FullAddress, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.FullAddress, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Checkout" class="btn btn-default" />
                    <a href="@Url.Action("ViewCart")" class="btn btn-primary">Back To Cart</a>
                </div>
            </div>
        </div>
    }
</div>

FYProject1/Views/Cart/ConfirmOrder.cshtml
@using FYProject1Classes
@using FYProject1Classes.FinalOrderMgmt
@using FYProject1Classes.UserMgmt
@model FYProject1Classes.FinalOrderMgmt.FinalOrder

@{
    ViewBag.Title = "ConfirmOrder";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
    User user = (User)Session[WebUtil.CURRENT_USER];
}

<h2 class="list-group-item-heading text-center">Confirm Order</h2>

<h4>Please confirm all Provided Details Properly before placing order!</h4>
<hr />
<div class="col-lg-9">
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FullAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FullAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        @if (user != null)
        {
            <dd>
                <a href="@Url.Action("UserGuestUpdate","User", new { id = user.Id})" class="btn btn-info">Update Details</a>
            </dd>
        }
        else
        {
            <dd>
                <a href="javascript:history.back()" class="btn btn-info">Update Details</a>
            </dd>
        }
    </dl>
    <hr />
    <table class="table table-bordered table-hover table-responsive table-striped">
        <tr>
            @*<th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ImageURL)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Price)
                </th>
                <th>
                    @Html.DisplayName("Discount")
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Quantity)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Amount)
                </th>
                <th></th>*@
        </tr>

        @if (Model != null)
        {
            foreach (var item in Model.ShoppingCartItem)
            {
                <tr class="text-center">
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        <a href="@Url.Action("ProductDetail","Home",new { id = item.Id})"><img src="@item.ImageURL" alt="prodimage" style="height: 50px;" /></a>
                    </td>
                    <td>
                        Rs. <b>@($"{item.Price:N0}")</b>
                    </td>
                    <td>
                        @item.Sale%
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Quantity)
                    </td>
                    <td>
                        Rs. <u>@($"{item.Amount:N0}")</u>
                    </td>
                </tr>
            }
        }
    </table>
    <div class="text-center">
        <a class="btn btn-primary" href="@Url.Action("ViewCart")">Back To Cart</a>
        <a class="btn btn-success" href="@Url.Action("Index","Home")">Shop More</a>
    </div>
    <div class="col-lg-4 pull-right">
        <h3><strong>TOTAL: </strong> <u>Rs. @($"{ViewBag.total:N0}")</u></h3>
        <a class="btn btn-default btn-block" href="@Url.Action("PlaceOrder",Model)">PLACE ORDER</a>
    </div>
</div>

FYProject1/Views/Cart/PlaceOrder.cshtml
@model FYProject1Classes.FinalOrderMgmt.FinalOrder

@{
    ViewBag.Title = "PlaceOrder";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<h2 class="text-center">Order Has been Placed Successfully!</h2>

<div class="col-lg-9 alert alert-success alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <strong>Success!</strong> Order Details has been mailed to <strong><em><u>@Model.Email</u></em></strong>.
</div>

FYProject1/Views/Cart/ViewCart.cshtml
@using FYProject1Classes
@using FYProject1Classes.CartManagment
@model IEnumerable<ShoppingCartItem>

@{
    ViewBag.Title = "ViewCart";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<h2 class="list-group-item-heading text-center notextselect">ViewCart</h2>

<div class="col-lg-9">
    <table class="table table-bordered table-hover table-responsive table-striped">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ImageURL)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayName("Discount")
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Quantity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Amount)
            </th>
            <th></th>
        </tr>

        @if (Model != null)
        {
            foreach (var item in Model)
            {
                <tr class="text-center">
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        <a href="@Url.Action(" ProductDetail","Home",new { id=item.Id})"><img src="@item.ImageURL" alt="prodimage" style="height: 50px;" /></a>
                    </td>
                    <td class="pricetd">
                        Rs. <b>@($"{item.Price:N0}")</b>
                    </td>
                    <td class="saletd">
                        @item.Sale%
                    </td>
                    <td class="cartqtytxt">
                        @Html.DisplayFor(modelItem => item.Quantity)
                    </td>
                    <td class="amounttd">
                        Rs. <u>@($"{item.Amount:N0}")</u>
                    </td>
                    <td>
                        @*@Html.ActionLink("Details", "Details", new { id = item.Id }) |*@
                        <a style="text-decoration:none" href="@Url.Action("RemoveFromCart",new{ id = item.Id})" class="fa fa-remove fa-2x"></a>
                    </td>
                </tr>
            }
        }
    </table>
    <div class="col-lg-4 pull-right">
        <h3><strong>TOTAL: </strong> <u>Rs. @($"{ViewBag.total:N0}")</u></h3>
        @if (ViewBag.total == 0 || ViewBag.total == null)
        {
            <a class="btn btn-danger btn-block disabled" href="#">Buy Something First!</a>
            <a class="btn btn-default btn-block" href="@Url.Action("Index","Home")">Home</a>
        }
        else
        {
            <a class="btn btn-default btn-block" href="@Url.Action("Checkout")">CHECKOUT</a>
        }
    </div>

</div>

@section myScript{
    <script type="text/javascript">
        setTimeout(() => {
            roar("<strong><u>Notice</u></strong>", "Demo Site For Testing Purpose Only<br/> Not Ready To Shop.", { confirmText: "Close" });
        }, 5000);

        var Tawk_API = Tawk_API || {}, Tawk_LoadStart = new Date();
        (function () {
            var s1 = document.createElement("script"), s0 = document.getElementsByTagName("script")[0];
            s1.async = true;
            s1.src = 'https://embed.tawk.to/5c5ae1fb7cf662208c944ffe/default';
            s1.charset = 'UTF-8';
            s1.setAttribute('crossorigin', '*');
            s0.parentNode.insertBefore(s1, s0);
        })();
    </script>
}

FYProject1/Views/Cart/email.cshtml
@model FYProject1Classes.FinalOrderMgmt.FinalOrder

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>email</title>
</head>
<body>
    <div>
    </div>
</body>
</html>