FYProject1/Models/recoveryEmail.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace FYProject1.Models
{
    public class recoveryEmail
    {
        [Required, Display(Name = "Email"), EmailAddress]
        public string Email { get; set; }
    }
}

FYProject1/Controllers/RecoveryEmailController.cs
using System;
using System.Web.Mvc;
using FYProject1.Models;
using System.Net.Mail;
using FYProject1Classes.LocationMgmt;
using System.Web.Security;
using System.IO;
using FYProject1Classes.UserMgmt;

namespace FYProject1.Controllers
{
    public class RecoveryEmailController : Controller
    {
        // GET: RecoveryEmail
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(recoveryEmail data)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    User user = new UserHandler().GetUserByEmail(data.Email);
                    if (user == null)
                    {
                        ViewBag.error = "Email Not Registered. Please Enter Registered Email Address";
                        return View();
                    }

                    string randomnumb = Path.GetRandomFileName().Replace(".", "");

                    var message = new MailMessage();
                    message.To.Add(new MailAddress(data.Email));
                    message.Subject = "-No-Reply- Password Recovery Email by [LK'- SHOP]";

                    // BODY Making Here to Send HTML page in email.

                    message.IsBodyHtml = true;

                    string body = string.Empty;
                    StreamReader reader = new StreamReader(Server.MapPath("~/Views/RecoveryEmail/email.html"));
                    using (reader)
                    {
                        body = reader.ReadToEnd();
                    }

                    body = body.Replace("{user}", user.FullName);
                    body = body.Replace("{random}", randomnumb);
                    body = body.Replace("[mail]", $"[{user.Email}]");

                    //message.Body = "Please use this password: " + randomnumb + " , Next Time You Login! And dont forget to change your password";
                    message.Body = body;

                    using (var smtp = new SmtpClient())
                    {
                        smtp.Send(message);
                        user.Password = randomnumb;
                        new UserHandler().UpdateUser(user);
                        ViewBag.success = "Email Has been sent to  " + data.Email;
                    }
                    return View();
                }
            }
            catch (Exception)
            {
                ViewBag.error = "Error Sending Mail. Please Try Again Later!";
            }

            return View();
        }
    }
}

FYProject1/Views/RecoveryEmail/Index.cshtml
@model FYProject1.Models.recoveryEmail

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />
<div class="container">
    <h2>Password Recovery</h2>
    <br />
    @using (Html.BeginForm("Index", "RecoveryEmail", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        <label>Enter Registered Email Address!</label>
        <div>
            @Html.TextBoxFor(e => e.Email, null, new { @class = "form-control" })
            @Html.ValidationMessageFor(e => e.Email, null, new { @class = "text-danger" })
            <br />
            @if (ViewBag.error != null)
            {
                <a class="btn btn-danger" href="@Url.Action("Index", "RecoveryEmail")"><span class="glyphicon glyphicon-refresh"></span> RETRY</a>
                <hr />
                <div class="alert alert-danger">@ViewBag.error</div>
            }
            else if (ViewBag.success != null)
            {
                <a class="btn btn-success" href="@Url.Action("Login", "User")"><span class="glyphicon glyphicon-check"></span> Login</a>
                <hr />
                <div class="alert alert-success">@ViewBag.success</div>
            }
            else
            {
                <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-send"></i> Send</button>
            }
        </div>

    }
</div>

@section myScript{
    <script type="text/javascript">
        var Tawk_API = Tawk_API || {}, Tawk_LoadStart = new Date();
        (function () {
            var s1 = document.createElement("script"), s0 = document.getElementsByTagName("script")[0];
            s1.async = true;
            s1.src = 'https://embed.tawk.to/5c5ae1fb7cf662208c944ffe/default';
            s1.charset = 'UTF-8';
            s1.setAttribute('crossorigin', '*');
            s0.parentNode.insertBefore(s1, s0);
        })();
    </script>
}