FYProject1/Controllers/LocationController.cs
using FYProject1Classes.LocationMgmt;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FYProject1Classes;

namespace FYProject1.Controllers
{
    public class LocationController : Controller
    {
        // -- Countries ---
        public ActionResult LocationManagment()
        {
            List<Country> countries = new LocationHandler().GetCountries();
            return View(countries);
        }

        public ActionResult AddCountry()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddCountry([Bind(Include = "Id,Name,CountryCode,Image_URL")] Country country)
        {
            if (ModelState.IsValid)
            {
                new LocationHandler().AddCountry(country);
                return RedirectToAction("LocationManagment");
            }
            return View(country);
        }

        public ActionResult DeleteCountry(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Country country = new LocationHandler().GetCountryById(id);
            if (country == null)
            {
                return HttpNotFound();
            }
            return View(country);
        }


        [HttpPost, ActionName("DeleteCountry")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteCountryConfirmed(int id)
        {
            Country country = new LocationHandler().GetCountryById(id);
            new LocationHandler().DeleteCountry(country);
            return RedirectToAction("LocationManagment");
        }

        // -- Cities ---

        public ActionResult CityList(int id)
        {
            List<City> cities = new LocationHandler().GetCitiesByCountryId(id);
            ViewBag.CountryID = id;
            ViewBag.CountryName = new LocationHandler().GetCountryById(id).Name;
            return View(cities);
        }

        public ActionResult AddCity(int id, string countryName)
        {
            ViewBag.CountryID = id;
            ViewBag.CountryName = countryName;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddCity([Bind(Include = "Id,Name")] City city, int id)
        {
            City c = new City();
            if (ModelState.IsValid)
            {
                c.Name = city.Name;
                c.Country = new LocationHandler().GetCountryById(id);
                new LocationHandler().AddCity(c);
                return RedirectToAction("CityList", new { Id = id });
            }
            return View();
        }

        public ActionResult DeleteCity(int? id, int countryId)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            City city = new LocationHandler().getCityById(id);

            if (city == null)
            {
                return HttpNotFound();
            }
            ViewBag.countryId = countryId;
            TempData["countryId"] = countryId;
            return View(city);
        }

        [HttpPost, ActionName("DeleteCity")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteCityConfirmed(int id)
        {
            City city = new LocationHandler().getCityById(id);
            new LocationHandler().DeleteCity(city);
            return RedirectToAction("CityList", new { Id = Convert.ToUInt32(TempData["countryId"]) });
        }

        public int GetCountriesCount()
        {
            return (new DBContextClass().Countries.Count());
        }

    }
}

FYProject1/Views/Shared/_AdminLayout.cshtml
@using FYProject1.Models
@using FYProject1Classes
@using FYProject1Classes.UserMgmt
@{
    User currentUser = (User)Session[WebUtil.CURRENT_USER];
}

<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="author" content="Arslan Ameer" />
    <meta name="description" content="LK-OnlineCameraShop" />

    <link href="~/bootstrap/css/bootstrap.css" rel="stylesheet" />
    <link href="~/bootstrap/css/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/font-awesome-4.7.0/css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />
    <link href="~/Content/datatables.min.css" rel="stylesheet" />
    <link href="~/Content/adminOview.css" rel="stylesheet" />
</head>

<body>


    <!-- TopBar (NAVBAR) -->

    <nav class="navbar navbar-default">
        <div class="container-fluid">

            <!-- Left Most Logo and Page TITLE -->

            <div class="navbar-header">
                <a href="~/Home/Index" class="navbar-brand">LK' <span class="fa fa-camera" aria-hidden="true"></span> Sh<i class="fa fa-spinner fa-spin" style="font-size:small"></i>p</a>
            </div>

            <!-- Next icons/Lists of Options in Unordered List Type -->

            <ul class="nav navbar-nav">
                <li> @Html.ActionLink("HOME", "Index", "Home") </li>
                <li><a href="#">What's Coming!</a></li>

                <!--Simple dropdown list in ul > li -->

                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Follow Us <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#"><span class="fa fa-facebook-official"></span>  Facebook</a></li>
                        <li><a href="#"><span class="fa fa-twitter"></span> Twitter</a></li>
                        <li><a href="#"><span class="fa fa-instagram"></span> Instagram</a></li>
                    </ul>
                </li>

                <!-- User Detail Dropdown with custom CSS -->
                @if (currentUser != null)
                {
                    <li class="dropdown notextselect">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="fa fa-user-circle-o fa-lg"></span> @currentUser.FullName <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>
                                <div class="navbar-login">
                                    <div class="row">
                                        <div class="col-lg-4">
                                            <div style="width:80px;height:95px">
                                                @foreach (var image in currentUser.UserImage)
                                                {
                                                    <img class="img-responsive img-rounded" style="width:100%; height:100%" alt="@image.Caption" src="@Url.Content(image.Url)" />
                                                }
                                            </div>
                                        </div>
                                        <div class="col-lg-8">
                                            <p class="text-left"><strong>@currentUser.FullName</strong></p>
                                            <p class="text-left small">@currentUser.Email</p>
                                            <p class="text-left">
                                                <a href="@Url.Action("UserGuestUpdate","User", new { id = currentUser.Id})" class="btn btn-default btn-block">UPDATE</a>
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            </li>
                        </ul>
                    </li>
                    if (currentUser.IsInRole(WebUtil.ADMIN_ROLE))
                    {
                        <li>@Html.ActionLink("Admin Panel", "AdminPanel", "Admin")</li>
                    }
                }
            </ul>

            <!-- Nav Bar Right Area Buttons -->

            <ul class="nav navbar-nav navbar-right">
                <li style="margin-top: 15px; margin-right: 50px; color: antiquewhite"><i class="lahore-temp"></i></li>
                <li style="font-size: 20px"><a href="@Url.Action("ViewCart", "cart")"><span class="fa fa-shopping-cart"></span> <i id="cartitems" style="font-size: 10px" class="badge">0</i></a></li>
                @if (currentUser != null)
                {
                    <li><a href="@Url.Action("Logout","User")"><span class="glyphicon glyphicon-log-out"></span> Logout </a></li>
                }
                else
                {
                    <li><a href="@Url.Action("SignUp","User")"><span class="fa fa-user-plus fa-lg"></span> SignUp</a></li>
                    <li><a href="@Url.Action("Login","User")"><span class="fa fa-sign-in fa-lg"></span> Login</a></li>
                }
            </ul>
        </div>
    </nav>



    <!-- Main Page BODY -->

    <div class="container">
        <div class="row">

            <!-- LEFT SECTION -->

            <div class="col-lg-3">
                <div class="list-group text-center notextselect">
                    <h3 class="list-group-item-heading text-center">ADMIN OPTI<i class="fa fa-gear fa-spin"></i>NS</h3>
                    @Html.ActionLink("Overview", "AdminPanel", "Admin", null, new { @class = "list-group-item" })
                    <a href="@Url.Action("AddProduct","Product")" class="list-group-item">ADD PRODUCT <i class="fa fa-plus"></i></a>
                    <a href="@Url.Action("ProductManagment","Product")" class="list-group-item"> Manage Products <i class="fa fa-camera"></i><i class="badge" style="font-size:x-small; margin-top:2px">@Html.Action("GetProductCount", "Product")</i></a>
                    <a href="@Url.Action("UserManagment","User")" class="list-group-item"> User managment <i class="fa fa-group"></i><i class="badge" style="font-size:x-small;margin-top:2px">@Html.Action("UserCount", "User")</i></a>
                    <a href="#" class="list-group-item">Placed Order <i class="fa fa-cart-arrow-down"></i></a>
                    <a href="@Url.Action("BannerManagment","Admin")" class="list-group-item"> Main Page Banners <span class="fa fa-image"></span><i class="badge" style="font-size:x-small;margin-top:2px">@Html.Action("GetBannerCount", "Admin")</i></a>
                    <a href="@Url.Action("LocationManagment","Location")" class="list-group-item">Location Managment <span class="fa fa-map-marker"></span><span class="badge" style="font-size:x-small;margin-top:2px">@Html.Action("GetCountriesCount", "Location")</span></a>
                </div>
            </div>

            <!-- RIGHT SECTION -->
            @RenderBody()

        </div>
    </div>
    <br />

    @*<div style="margin-top:20px"></div>*@




    <!-- Bottom Bar / Footer -->

    <footer class="navbar navbar-default" style="margin:0px">
        <div class="container">

            <p class="navbar-text pull-left notextselect" style="color:antiquewhite; cursor:default">Copyrights &copy; Arslan Ameer | All Rights Reserved</p>
            <ul class="nav navbar-nav">
                <li><a href="#">About Us</a></li>
                <li><a href="#">Contact Us</a></li>
                <li><a href="#">Our Partners</a></li>
                <li><a href="#">Terms & Conditions</a></li>
                <li><a href="#">Payment Methods</a></li>
            </ul>

            <a href="#" class="navbar-btn btn-default btn pull-right"><span class="glyphicon glyphicon-menu-up"></span></a>

            <div class="navbar-text pull-right">
                <ul class="nav nav-pills" style="color:antiquewhite">
                    <li> <span class="fa fa-cc-visa"> </span> </li>
                    <li> <span class="fa fa-cc-mastercard"> </span> </li>
                    <li> <span class="fa fa-cc-amex"> </span> </li>
                    <li> <span class="fa fa-cc-paypal"> </span> </li>
                </ul>
            </div>
        </div>
    </footer>

    <!-- Scripting Here -->

    <script src="~/Scripts/jquery-2.2.3.min.js"></script>
    <script src="~/Scripts/jquery-2.2.3.intellisense.js"></script>
    <script src="~/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
    <script src="~/Scripts/datatables.min.js"></script>
    <script src="~/Scripts/ImagePreview.js"></script>
    <script src="~/Scripts/blazy.min.js"></script>

    <script type="text/javascript">
        $(function () {

            var bLazy = new Blazy();

            $('#datatable').DataTable();

            const apiKey = "4a9232de37b1880944eb4e365aa69011";
            const url = `https://api.openweathermap.org/data/2.5/weather?APPID=${apiKey}&units=metric&q=lahore,pk`;

            var temp = document.querySelector(".lahore-temp");

            function apiCall() {
                fetch(url).then((response) => {
                    return response.json();
                }).then((data) => {
                    temp.innerHTML = data.main.temp_max + "&deg;C";
                }).catch((error) => {
                    console.log(error);
                });
            };

            setInterval(apiCall(), 300000);


            $.ajax(
                {
                    url: "/Cart/ItemsCount",
                    type: "get"
                }).done(function (itemscount) {
                    $("#cartitems").text(itemscount);
                });

            $(".cartqtytxt").change(function () {
                var elt = $(this);
                var qty = elt.val();
                if (qty !== 0) {
                    var qs = "?id=" + $(this).data("pid") + "&qty=" + qty;
                    $.ajax({
                        url: "/Cart/UpdateToCart" + qs,
                        type: "get"
                    }).done(function (itemscount) {
                        $("#cartitems").text(itemscount);
                    });
                }
            });

            $(".addcartbtn").click(function () {
                var obj = {
                    "Id": $(this).data("pid"),
                    "Name": $(this).data("pname"),
                    "Price": $(this).data("pprice"),
                    "Quantity": $(this).data("pqty"),
                    "ImageURL": $(this).data("purl"),
                    "Sale": $(this).data("psale")
                }
                $(this).parents("#proditem").fadeOut(100);
                $.ajax(
                    {
                        url: "/Cart/AddToCart",
                        type: "get",
                        data: obj
                    }
                ).done(function (itemscount) {
                    $("#cartitems").text(itemscount);
                });

                $(this).parents("#proditem").fadeIn(100);
            });
        });
    </script>
    @RenderSection("myScript", false)

</body>
</html>

FYProject1/Views/Shared/_DDLView.cshtml
@using FYProject1.Models
@model FYProject1.Models.DDViewModel

@Html.DropDownList(Model.Name, Model.Values, Model.Label, new { @class = "form-control", style = "Width:130px; Float: Right", name = "CityList" })

FYProject1/Views/Shared/_DDLViewBoot.cshtml
@using FYProject1.Models
@model FYProject1.Models.DDViewModel

@Html.DropDownList(Model.Name, Model.Values, Model.Label, new { @class = "form-control text-center"})

FYProject1/Views/Shared/_Layout.cshtml
@using FYProject1.Models
@using FYProject1Classes
@using FYProject1Classes.UserMgmt


@{
    User currentUser = (User)Session[WebUtil.CURRENT_USER];
}


<!Doctype html>
<html lang="en-us">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link href="~/Content/Main.css" rel="stylesheet" />
    <link href="~/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/bootstrap/css/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/Content/jquery-ui.css" rel="stylesheet" />
    <style type="text/css">
        @RenderSection("CustomStyles", false)
    </style>

</head>

<body>

    <!-- ---------- Top BAR ---------- -->

    <div class="topbar" style="font-style:italic">

        <div class="topbarlogo">
            @*<img src="~/Content/linkedin.png" alt="Logo" width="28"/>*@
            <a href="@Url.Action("Index","Home")" style="color:antiquewhite"><h5>LK <i class="glyphicon glyphicon-camera"></i> Shop</h5></a>
        </div>

        <div class="topbararea">
            @if (currentUser != null)
            {
                <div>
                    | Welcome
                    <a style="color:silver; font-style:normal; font-size:15px; font-weight:500; cursor:pointer">
                        <i class="glyphicon glyphicon-user"></i>
                        @currentUser.FullName
                    </a> |

                    @Html.ActionLink("Home", null, new { style = "color: antiquewhite" })
                    @Html.ActionLink("Logout", "Logout", "User", null, new { style = "color: antiquewhite; float: right" }) |

                    @if (currentUser.IsInRole(WebUtil.ADMIN_ROLE))
                    {
                        @Html.ActionLink("Admin Panel", "Admin", "Home", null, new { style = " color: antiquewhite" })
                    }


                </div>
            }
            else
            {
                <div style="float: right">
                    <i class="lahore-temp"></i>
                    @Html.ActionLink("Login", "Login", "User", null, new { style = "color: antiquewhite" }) |
                    @Html.ActionLink("SignUp", "SignUp", "User", null, new { style = "color: antiquewhite" })
                </div>
                <div>@Html.ActionLink("Home", "Index", "Home", null, new { style = "color: antiquewhite" })</div>
                <div class="clearsec"></div>
            }




        </div>
    </div><div class="clearsec"></div>

    <!-- ---------- Central Work Area ---------- -->
    <div>
        @RenderBody()
    </div>

    <!-- ---------- BOTTOM BAR ---------- -->

    <div class="bottombar navbar-fixed-bottom" style="margin-top:11px">
        <div class="bottombararea">
            <small>&copy; Copyright | [LK']-Stud!os &trade; | Arslan Ameer</small>
        </div>
    </div>

    <!-- ------------ Java Scripting Here ------------ -->

    <script src="~/Scripts/jquery-2.2.3.intellisense.js"></script>
    <script src="~/Scripts/jquery-2.2.3.min.js"></script>
    <script src="../../bootstrap/js/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

    <script type="text/javascript">
        const apiKey = "4a9232de37b1880944eb4e365aa69011";
        const url = `https://api.openweathermap.org/data/2.5/weather?APPID=${apiKey}&units=metric&q=lahore,pk`;

        var temp = document.querySelector(".lahore-temp");


        function apiCall() {
            fetch(url).then((response) => {
                return response.json();
            }).then((data) => {
                temp.innerHTML = data.main.temp_max + "&deg;C";
            }).catch((error) => {
                console.log(error);
            });
        };

        setInterval(apiCall(), 300000);

    </script>
    @RenderSection("MyScript", false)

</body>
</html>